### ISSUE TITLE
[Question] What does "Huge Page Allocation Ratio" mean in Section 6.2

### ISSUE THREAD

**Issue by YalandHong** [casys-kaist/AMP#1]
Hello,

This is actually not an issue, but a question about the paper.

Recently I'm reading your paper about AMP. It's really impressive. However, in Section 6.2, you say that the workloads present high huge page allocation ratio, which bewilders me somewhat. I have searched the word "allocation" in your paper but I can't find its definition.

So, what does "huge page allocation ratio" mean? Could you please explain it more detailedly?

Thanks!

Yaland Hong

![image](https://user-images.githubusercontent.com/52960068/107454752-94bbec00-6b88-11eb-955b-3e496a684ca3.png)

**Comment by TaekyungHeo** [comment]
Dear Yaland.

Thank you for having an interest in our work.

We enabled transparent huge pages (THP) of the Linux kernel to use huge pages.
THP does not guarantee huge page allocation, and the kernel may return 4KB base pages if it fails to find physically contiguous 2MB-aligned free memory.

The huge page allocation ratio presents how much of allocated memory is backed by huge pages.
It is defined as (allocated memory size backed by 2MB huge pages / allocated memory size) * 100.

**Comment by YalandHong** [comment]
Hello Dr.Heo,

Thanks for your explanation!

I still have another question about this section. In Figure 10, you compare the performace between "modified LRU list" and "LRU". What's the difference between them? What does "LRU" refer to? Does it mean Linux's active/inactive list or "real" LRU policy (i.e. track every memory access and move list nodes accordingly) ?

![image](https://user-images.githubusercontent.com/52960068/107603152-d6bb5f80-6c66-11eb-8970-63edfb906b5f.png)

**Comment by TaekyungHeo** [comment]
The modified LRU lists refer to the prior study that I have mentioned in Section 3.3.
(Nimble Page Management for Tiered Memory Systems, https://dl.acm.org/doi/10.1145/3297858.3304024)

LRU, LFU, and Random are the migration policies that I have described at the end of Section 3.1. LRU in the legend is different from the native Linux's active / inactive lists.

**Comment by YalandHong** [comment]
OK, thanks.

Besides, for some reason, Figure 10 doesn't show the "favor" for `geomean`, nor does Figure 2. I also see a dotted line near `geomean` in Figure 5 and Figure 7, and bold font in Table 3.

Is there something special with this workload?

![image](https://user-images.githubusercontent.com/52960068/107609637-7e8e5880-6c7a-11eb-825e-85353d745baa.png)
![image](https://user-images.githubusercontent.com/52960068/107609693-b4cbd800-6c7a-11eb-8710-6cd8f274fa2b.png)

**Comment by YalandHong** [comment]
Ok. Thanks!
